---
- group:
    name: "{{ node_exporter_user }}"
    system: yes

- user:
    name: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    home: "{{ node_exporter_deploy_dir }}"
    createhome: no

- get_url:
    url: "{{ node_exporter_archive_url }}"
    dest: "{{ ansible_cache_dir }}/{{ node_exporter_archive_name }}"
    sha256sum: "{{ node_exporter_archive_sum[node_exporter_version] }}"

- unarchive:
    src: "{{ ansible_cache_dir }}/{{ node_exporter_archive_name }}"
    dest: "{{ node_exporter_unarchive_dir }}/"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    copy: no

- file:
    src: "{{ node_exporter_unarchive_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64"
    state: link
    dest: "{{ node_exporter_deploy_dir }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"

- template:
    src: node_exporter.service.j2
    dest: /lib/systemd/system/node_exporter.service
  register: node_exporter_service

- template:
    src: consul.service.json.j2
    dest: /etc/consul.d/node_exporter.json
  notify: restart consul

- shell: >
    systemctl daemon-reload
  when: node_exporter_service|changed
  notify: restart node_exporter

- service:
    name: node_exporter
    state: started
    enabled: yes

- file:
    path: "{{ node_exporter_deploy_dir }}/txt"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"

- copy:
    dest: "{{ node_exporter_deploy_dir }}/txt/host.prom"
    content: |
      host{hostname="{{ ansible_hostname }}"} 1
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
  notify: restart node_exporter

- meta: flush_handlers